[package]
name = "azure_oauth_rs"
version = "0.1.0"
authors = ["Carl Fredrik Samson <cf@samson.no>"]
edition = "2018"

[dependencies]
jsonwebtoken = "5.0.1"
reqwest = "0.9.14"
serde = {version="1.0.90", features=["derive"]}
chrono = "0.4.6"
base64 = "0.10.1"
