[package]
name = "azure_auth_rs"
version = "0.1.0"
authors = ["Carl Fredrik Samson <cf@samson.no>"]
edition = "2018"

[dependencies]
jwt = "0.4.0"
rust-crypto = "0.2.36"
reqwest = "0.9.14"
serde = {version="1.0.90", features=["derive"]}
chrono = "0.4.6"
