[package]
name = "azure_jwt"
version = "0.2.1"
authors = ["Carl Fredrik Samson <cf@samson.no>"]
edition = "2018"
repository = "https://github.com/cfsamson/azure-jwt"
documentation = "https://docs.rs/azure-jwt/"
readme = "README.md"
license = "MIT"
keywords = ["azure", "token", "jwt", "jwk", "validation"]
categories = ["authentication"]
description = """
A simple JWT validator for Microsoft Azure Id tokens.
"""

[dependencies]
jsonwebtoken = "7.2.0"
reqwest = {version = "0.11.1", default-features = false, features = ["blocking", "json"]}
serde = { version = "1.0.124", features = ["derive"] }
chrono = "0.4.19"

[dev-dependencies]
criterion = "0.3.4"
base64 = "0.13.0"

[[bench]]
name = "validation"
harness = false
