[package]
name = "azure_jwt"
version = "0.1.4"
authors = ["Carl Fredrik Samson <cf@samson.no>"]
edition = "2018"
repository = "https://github.com/cfsamson/azure-jwt"
documentation = "https://docs.rs/azure-jwt/"
readme = "README.md"
license = "MIT"
keywords = ["azure", "token", "jwt", "jwk", "validation"]
categories = ["authentication"]
description = """
A simple JWT validator for Microsoft Azure Id tokens.
"""

[dependencies]
jsonwebtoken = "5.0.1"
reqwest = "0.9.14"
serde = {version="1.0.90", features=["derive"]}
chrono = "0.4.6"
base64 = "0.10.1"

[target.'cfg(not(vendored))'.dependencies]
openssl = {version="0.10.20"}

[target.'cfg(vendored)'.dependencies]
openssl = {version="0.10.20", features=["vendored"]}

[target.'cfg(windows)'.dependencies]
openssl-probe = "0.1.2"

[features]
vendored = []


[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "validation"
harness = false
