on: [pull_request, push]

name: Rust

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: --all-features
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        name: Check formatting
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Security audit
        with:
          command: audit
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all-features